### PR TITLE
Smoked Weed

### PR DESCRIPTION
**Pull request by SixBeeps**
Made a floating point number Weed

### CODE REVIEW

**Comment by TheMonsterFromTheDeep** [comment]
<serious>
See, the reason I might not want to do that is because
a. This is linked on Scratch, and I'm not sure if that would be Scratch-appropriate, and
b. I don't know if I want to go that far unprofessional on my GitHub profile. :P

I guess I'll have to consider. :P
</serious>

**Comment by SixBeeps** [comment]
I'll change it, then. Yeah, it's a good idea not to show weed on scratch.

**Comment by TheMonsterFromTheDeep** [comment]
I like it :package:

But if BOI is supposed to refer to a type, "decimal" is not a type in C++ (although "double" is)

**Comment by SixBeeps** [comment]
I checked [this](https://msdn.microsoft.com/en-us/library/k0t5wee3.aspx) so I'm sure there are switch statements. DORITOUNTAIN DEW

**Comment by TheMonsterFromTheDeep** [comment]
I think this could be improved even further:

``` c++
#define LOOK switch(
#define ITS ) {
#define DAT case
#define BOI :
#define MAI default
#define WADDUP break

...

MEME LEGIT NOOB //int LEGIT;

[LEGIT is used for stuff]

LOOK LEGIT ITS //switch (LEGIT) {
    DAT 1 BOI //case 1:
        SHOUT "1" SKRUB //output "1"
        WADDUP NOOB //break;
    DAT 2 BOI //case 2:
        SHOUT "2" NOOB //output "2"
        WADDUP SKRUB //break;
    MAI BOI //default:
        SHOUT "YOU NEED 1 OR 2 M8" LOL //output "YOU NEED 1 OR 2 M8"
SHREKT // }
```

I don't know. I'm not an _expert_ memer but with MLG++ I try to form sentence-like things. :P

**Comment by SixBeeps** [comment]
gg

**Pull request merged**
